### ISSUE TITLE
tiptap integration

### ISSUE THREAD

**Issue by philippkuehn** [quartzy/prosemirror-suggestions#5]
Hey @tristanpemble,

this is not a issue, but I haven't found any other way to reach you. I am the creator of [tiptap - a prosemirror editor for Vue](https://github.com/heyscrumpy/tiptap). I would like to integrate Mentions and Tags and have seen that you have already done a great job here. 🙌 I would like to integrate prosemirror-suggestions directly but I would have to make some changes. So the question of whether I can use parts of the code? Of course I would name you in the Readme and give you endless hugs! ✌️

**Comment by tristanpemble** [comment]
hey @philippkuehn, thanks for asking :) if there are requirements for tiptap that prosemirror-suggestions doesn't meet, I'd be interested in hearing what you need to change in order to use it there. you're totally free to use the code however you like (with appropriate attribution under the Apache license, the details which I'm admittedly not totally clear on), but I think it'd be great if we could make this package useful for a wider variety of use cases. I've so far not received any feedback about how others are using this plugin, so I'm excited to hear about your story!

**Comment by philippkuehn** [comment]
Hey, sounds great. I try to implement this into tiptap and get back to you later to see what modifications were necessary on my site. Maybe you can change it here in this package, so we don't have to do some work twice. 👍
